this is my program 1 statement
this is my program 2 statement
this is my program 3 statement
this is my program 4 statement
this line i have written in feature branch
this  is my first line ....
this is my second line.....
this is my third line....
git  remote remove origin..enter
git remote add origin"path"... enter
git push origin master.. enter
editing in git hub...
